CREATE TABLE "GCG_3343_HOURS_SMRY"(
 "TERMINAL" CHAR(3),
 "EMPLOYEE" CHAR(5),
 "EMPLOYEE_NAME" CHAR(50),
 "SHIFT" CHAR(1),
 "DEPT_EMPLOYEE" CHAR(4),
 "HOURS" CHAR(20),
 "TYPE" CHAR(2),
 "EC" CHAR(5),
 "DESCRIPTION" CHAR(30),
 "REASON" CHAR(30),
 "BALANCING_GROUP" CHAR(8));